### ISSUE TITLE
As a player, I can log in to an existing account

### ISSUE THREAD

**Issue by IlanMalk** [witseie-elen4010/2022-group-lab-001#18]

**Comment by IlanMalk** [comment]
# Tasks
- [ ] Create front end with username and password field, as well as submit button
- [ ] Create basic validation function: valid logins are hard-coded
- [ ] Create persistent storage and adapt validation function to get data from persistent storage
- [ ] Hash passwords

**Comment by IlanMalk** [comment]
# Acceptance Tests

- [ ] Enter valid username and password (e.g. username = "admin", password = "user"): 'Login successful' should be displayed and main menu should load
- [ ] Enter invalid username and password. 'Login not successful' should display and user should remain on login page
